# fly.toml app configuration file generated for nwc on 2024-01-30T12:30:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nwc'
primary_region = 'lax'
swap_size_mb = 2048
# Add a kill timeout 30s longer than LDK node shutdown timeout
kill_timeout = 300

[build]
  image = 'ghcr.io/getalby/hub:latest'

[env]
  DATABASE_URI = '/data/nwc.db'
  LDK_LOG_LEVEL = '3'
  LOG_LEVEL = '4'
  WORK_DIR = '/data'

[[mounts]]
  source = 'nwc_data'
  destination = '/data'
  initial_size = '1'
  auto_extend_size_threshold = 80
  auto_extend_size_increment = "1GB"
  auto_extend_size_limit = "5GB"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory = '512mb'
