name: Wails build
on:
  push:
  release:
    types: [published]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          [
            {
              name: nostr-wallet-connect,
              platform: linux/amd64,
              os: ubuntu-latest,
            },
          ]
    env:
      REGISTRY: ghcr.io
      IMAGENAME: ${{ github.event.repository.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
      - name: Setup GoLang
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: 1.21
      # Setup and configure NodeJS
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
        shell: bash
      - name: Install Linux Wails deps
        run: sudo apt-get update && sudo apt-get install libgtk-3-0 libwebkit2gtk-4.0-dev gcc-aarch64-linux-gnu libgtk-3-dev nsis
        shell: bash
      - name: Wails Doctor
        working-directory: .
        run: wails doctor
        shell: bash
      # Building step
      - name: Build App
        working-directory: .
        run: wails build --platform ${{ matrix.build.platform }} -tags "wails"
        #-o ${{ matrix.build.name }}
        shell: bash
      - uses: actions/upload-artifact@v3
        with:
          name: Wails Build ${{runner.os}} nostr-wallet-connect
          path: |
            */bin/
            *\bin\*

#      - uses: dAppServer/wails-build-action@v2.2
#        with:
#          build-name: ${{ matrix.build.name }}
#          build-platform: ${{ matrix.build.platform }}
#          package: false
#          go-version: '1.21'
